name: code-checker

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-check-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          pip3 install --upgrade pip
          pip3 install pyflakes
          pip3 install black
          pip3 install isort

      - name: Detect errors with pyflakes
        run: pyflakes TwitchChannelPointsMiner

      - name: Lint with black
        run: black TwitchChannelPointsMiner --check --diff

      - name: Lint with isort
        run: isort TwitchChannelPointsMiner --profile black --check --diff
